
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Mar 13 2026 03:30:56 +06 (Mar 12 2026 21:30:56 UTC)

// Verification Directory fv/top 

module top(clk, a, b, op, y);
  input clk;
  input [31:0] a, b;
  input [2:0] op;
  output [31:0] y;
  wire clk;
  wire [31:0] a, b;
  wire [2:0] op;
  wire [31:0] y;
  wire [31:0] b_reg;
  wire [31:0] a_reg;
  wire [2:0] op_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_290, u_alu_n_363, u_alu_n_364,
       u_alu_n_365;
  wire u_alu_n_366, u_alu_n_367, u_alu_n_368, u_alu_n_369, u_alu_n_370,
       u_alu_n_371, u_alu_n_372, u_alu_n_373;
  wire u_alu_n_374, u_alu_n_375, u_alu_n_376, u_alu_n_377, u_alu_n_378,
       u_alu_n_379, u_alu_n_380, u_alu_n_381;
  wire u_alu_n_382, u_alu_n_383, u_alu_n_384, u_alu_n_385, u_alu_n_386,
       u_alu_n_387, u_alu_n_388, u_alu_n_389;
  wire u_alu_n_390, u_alu_n_391, u_alu_n_392, u_alu_n_393, u_alu_n_394,
       u_alu_sub_11_23_Y_add_10_23_n_773,
       u_alu_sub_11_23_Y_add_10_23_n_775,
       u_alu_sub_11_23_Y_add_10_23_n_777;
  wire u_alu_sub_11_23_Y_add_10_23_n_779,
       u_alu_sub_11_23_Y_add_10_23_n_781,
       u_alu_sub_11_23_Y_add_10_23_n_783,
       u_alu_sub_11_23_Y_add_10_23_n_785,
       u_alu_sub_11_23_Y_add_10_23_n_787,
       u_alu_sub_11_23_Y_add_10_23_n_789,
       u_alu_sub_11_23_Y_add_10_23_n_791,
       u_alu_sub_11_23_Y_add_10_23_n_793;
  wire u_alu_sub_11_23_Y_add_10_23_n_795,
       u_alu_sub_11_23_Y_add_10_23_n_797,
       u_alu_sub_11_23_Y_add_10_23_n_799,
       u_alu_sub_11_23_Y_add_10_23_n_801,
       u_alu_sub_11_23_Y_add_10_23_n_803,
       u_alu_sub_11_23_Y_add_10_23_n_805,
       u_alu_sub_11_23_Y_add_10_23_n_807,
       u_alu_sub_11_23_Y_add_10_23_n_809;
  wire u_alu_sub_11_23_Y_add_10_23_n_811,
       u_alu_sub_11_23_Y_add_10_23_n_813,
       u_alu_sub_11_23_Y_add_10_23_n_815,
       u_alu_sub_11_23_Y_add_10_23_n_817,
       u_alu_sub_11_23_Y_add_10_23_n_819,
       u_alu_sub_11_23_Y_add_10_23_n_821,
       u_alu_sub_11_23_Y_add_10_23_n_823,
       u_alu_sub_11_23_Y_add_10_23_n_825;
  wire u_alu_sub_11_23_Y_add_10_23_n_827,
       u_alu_sub_11_23_Y_add_10_23_n_829,
       u_alu_sub_11_23_Y_add_10_23_n_831,
       u_alu_sub_11_23_Y_add_10_23_n_833,
       u_alu_sub_11_23_Y_add_10_23_n_834,
       u_alu_sub_11_23_Y_add_10_23_n_835,
       u_alu_sub_11_23_Y_add_10_23_n_837,
       u_alu_sub_11_23_Y_add_10_23_n_838;
  wire u_alu_sub_11_23_Y_add_10_23_n_839,
       u_alu_sub_11_23_Y_add_10_23_n_840,
       u_alu_sub_11_23_Y_add_10_23_n_841,
       u_alu_sub_11_23_Y_add_10_23_n_842,
       u_alu_sub_11_23_Y_add_10_23_n_843,
       u_alu_sub_11_23_Y_add_10_23_n_844,
       u_alu_sub_11_23_Y_add_10_23_n_845,
       u_alu_sub_11_23_Y_add_10_23_n_846;
  wire u_alu_sub_11_23_Y_add_10_23_n_847,
       u_alu_sub_11_23_Y_add_10_23_n_848,
       u_alu_sub_11_23_Y_add_10_23_n_849,
       u_alu_sub_11_23_Y_add_10_23_n_850,
       u_alu_sub_11_23_Y_add_10_23_n_851,
       u_alu_sub_11_23_Y_add_10_23_n_852,
       u_alu_sub_11_23_Y_add_10_23_n_853,
       u_alu_sub_11_23_Y_add_10_23_n_854;
  wire u_alu_sub_11_23_Y_add_10_23_n_855,
       u_alu_sub_11_23_Y_add_10_23_n_856,
       u_alu_sub_11_23_Y_add_10_23_n_857,
       u_alu_sub_11_23_Y_add_10_23_n_858,
       u_alu_sub_11_23_Y_add_10_23_n_859,
       u_alu_sub_11_23_Y_add_10_23_n_860,
       u_alu_sub_11_23_Y_add_10_23_n_861,
       u_alu_sub_11_23_Y_add_10_23_n_862;
  wire u_alu_sub_11_23_Y_add_10_23_n_863,
       u_alu_sub_11_23_Y_add_10_23_n_864,
       u_alu_sub_11_23_Y_add_10_23_n_865,
       u_alu_sub_11_23_Y_add_10_23_n_866,
       u_alu_sub_11_23_Y_add_10_23_n_867;
  DFFX1 \b_reg_reg[28] (.CK (clk), .D (b[28]), .Q (b_reg[28]), .QN
       (UNCONNECTED));
  DFFX1 \a_reg_reg[30] (.CK (clk), .D (a[30]), .Q (a_reg[30]), .QN
       (n_5));
  DFFX1 \a_reg_reg[28] (.CK (clk), .D (a[28]), .Q (a_reg[28]), .QN
       (n_3));
  DFFX1 \a_reg_reg[16] (.CK (clk), .D (a[16]), .Q (a_reg[16]), .QN
       (n_18));
  DFFX1 \b_reg_reg[0] (.CK (clk), .D (b[0]), .Q (b_reg[0]), .QN
       (UNCONNECTED0));
  DFFX1 \a_reg_reg[0] (.CK (clk), .D (a[0]), .Q (a_reg[0]), .QN
       (UNCONNECTED1));
  DFFX1 \a_reg_reg[24] (.CK (clk), .D (a[24]), .Q (a_reg[24]), .QN
       (n_24));
  DFFX1 \b_reg_reg[19] (.CK (clk), .D (b[19]), .Q (b_reg[19]), .QN
       (UNCONNECTED2));
  DFFX1 \b_reg_reg[31] (.CK (clk), .D (b[31]), .Q (b_reg[31]), .QN
       (UNCONNECTED3));
  DFFX1 \a_reg_reg[15] (.CK (clk), .D (a[15]), .Q (a_reg[15]), .QN
       (n_8));
  DFFX1 \b_reg_reg[30] (.CK (clk), .D (b[30]), .Q (b_reg[30]), .QN
       (UNCONNECTED4));
  DFFX1 \b_reg_reg[20] (.CK (clk), .D (b[20]), .Q (b_reg[20]), .QN
       (UNCONNECTED5));
  DFFX1 \a_reg_reg[10] (.CK (clk), .D (a[10]), .Q (a_reg[10]), .QN
       (n_15));
  DFFX1 \b_reg_reg[29] (.CK (clk), .D (b[29]), .Q (b_reg[29]), .QN
       (UNCONNECTED6));
  DFFX1 \a_reg_reg[23] (.CK (clk), .D (a[23]), .Q (a_reg[23]), .QN
       (UNCONNECTED7));
  DFFX1 \a_reg_reg[14] (.CK (clk), .D (a[14]), .Q (a_reg[14]), .QN
       (n_16));
  DFFX1 \a_reg_reg[31] (.CK (clk), .D (a[31]), .Q (a_reg[31]), .QN
       (UNCONNECTED8));
  DFFX1 \b_reg_reg[27] (.CK (clk), .D (b[27]), .Q (b_reg[27]), .QN
       (UNCONNECTED9));
  DFFX1 \a_reg_reg[13] (.CK (clk), .D (a[13]), .Q (a_reg[13]), .QN
       (n_10));
  DFFX1 \b_reg_reg[26] (.CK (clk), .D (b[26]), .Q (b_reg[26]), .QN
       (UNCONNECTED10));
  DFFX1 \b_reg_reg[25] (.CK (clk), .D (b[25]), .Q (b_reg[25]), .QN
       (UNCONNECTED11));
  DFFX1 \a_reg_reg[27] (.CK (clk), .D (a[27]), .Q (a_reg[27]), .QN
       (n_7));
  DFFX1 \a_reg_reg[22] (.CK (clk), .D (a[22]), .Q (a_reg[22]), .QN
       (UNCONNECTED12));
  DFFX1 \a_reg_reg[12] (.CK (clk), .D (a[12]), .Q (a_reg[12]), .QN
       (n_23));
  DFFX1 \b_reg_reg[24] (.CK (clk), .D (b[24]), .Q (b_reg[24]), .QN
       (UNCONNECTED13));
  DFFX1 \b_reg_reg[23] (.CK (clk), .D (b[23]), .Q (b_reg[23]), .QN
       (UNCONNECTED14));
  DFFX1 \a_reg_reg[11] (.CK (clk), .D (a[11]), .Q (a_reg[11]), .QN
       (n_4));
  DFFX1 \b_reg_reg[22] (.CK (clk), .D (b[22]), .Q (b_reg[22]), .QN
       (UNCONNECTED15));
  DFFX1 \b_reg_reg[21] (.CK (clk), .D (b[21]), .Q (b_reg[21]), .QN
       (UNCONNECTED16));
  DFFX1 \a_reg_reg[21] (.CK (clk), .D (a[21]), .Q (a_reg[21]), .QN
       (UNCONNECTED17));
  DFFX1 \op_reg_reg[1] (.CK (clk), .D (op[1]), .Q (op_reg[1]), .QN
       (n_11));
  DFFX1 \op_reg_reg[0] (.CK (clk), .D (op[0]), .Q (op_reg[0]), .QN
       (UNCONNECTED18));
  DFFX1 \op_reg_reg[2] (.CK (clk), .D (op[2]), .Q (op_reg[2]), .QN
       (n_13));
  DFFX1 \a_reg_reg[9] (.CK (clk), .D (a[9]), .Q (a_reg[9]), .QN
       (UNCONNECTED19));
  DFFX1 \b_reg_reg[18] (.CK (clk), .D (b[18]), .Q (b_reg[18]), .QN
       (UNCONNECTED20));
  DFFX1 \b_reg_reg[17] (.CK (clk), .D (b[17]), .Q (b_reg[17]), .QN
       (UNCONNECTED21));
  DFFX1 \a_reg_reg[29] (.CK (clk), .D (a[29]), .Q (a_reg[29]), .QN
       (n_21));
  DFFX1 \a_reg_reg[26] (.CK (clk), .D (a[26]), .Q (a_reg[26]), .QN
       (UNCONNECTED22));
  DFFX1 \a_reg_reg[20] (.CK (clk), .D (a[20]), .Q (a_reg[20]), .QN
       (n_26));
  DFFX1 \a_reg_reg[8] (.CK (clk), .D (a[8]), .Q (a_reg[8]), .QN
       (UNCONNECTED23));
  DFFX1 \b_reg_reg[16] (.CK (clk), .D (b[16]), .Q (b_reg[16]), .QN
       (UNCONNECTED24));
  DFFX1 \b_reg_reg[15] (.CK (clk), .D (b[15]), .Q (b_reg[15]), .QN
       (UNCONNECTED25));
  DFFX1 \a_reg_reg[7] (.CK (clk), .D (a[7]), .Q (a_reg[7]), .QN (n_6));
  DFFX1 \b_reg_reg[14] (.CK (clk), .D (b[14]), .Q (b_reg[14]), .QN
       (UNCONNECTED26));
  DFFX1 \b_reg_reg[13] (.CK (clk), .D (b[13]), .Q (b_reg[13]), .QN
       (UNCONNECTED27));
  DFFX1 \a_reg_reg[19] (.CK (clk), .D (a[19]), .Q (a_reg[19]), .QN
       (n_2));
  DFFX1 \a_reg_reg[6] (.CK (clk), .D (a[6]), .Q (a_reg[6]), .QN (n_20));
  DFFX1 \b_reg_reg[12] (.CK (clk), .D (b[12]), .Q (b_reg[12]), .QN
       (UNCONNECTED28));
  DFFX1 \b_reg_reg[11] (.CK (clk), .D (b[11]), .Q (b_reg[11]), .QN
       (UNCONNECTED29));
  DFFX1 \a_reg_reg[5] (.CK (clk), .D (a[5]), .Q (a_reg[5]), .QN (n_19));
  DFFX1 \b_reg_reg[10] (.CK (clk), .D (b[10]), .Q (b_reg[10]), .QN
       (UNCONNECTED30));
  DFFX1 \b_reg_reg[9] (.CK (clk), .D (b[9]), .Q (b_reg[9]), .QN (n_12));
  DFFX1 \a_reg_reg[25] (.CK (clk), .D (a[25]), .Q (a_reg[25]), .QN
       (n_17));
  DFFX1 \a_reg_reg[18] (.CK (clk), .D (a[18]), .Q (a_reg[18]), .QN
       (UNCONNECTED31));
  DFFX1 \a_reg_reg[4] (.CK (clk), .D (a[4]), .Q (a_reg[4]), .QN (n_1));
  DFFX1 \b_reg_reg[8] (.CK (clk), .D (b[8]), .Q (b_reg[8]), .QN
       (UNCONNECTED32));
  DFFX1 \b_reg_reg[7] (.CK (clk), .D (b[7]), .Q (b_reg[7]), .QN
       (UNCONNECTED33));
  DFFX1 \a_reg_reg[3] (.CK (clk), .D (a[3]), .Q (a_reg[3]), .QN (n_22));
  DFFX1 \b_reg_reg[6] (.CK (clk), .D (b[6]), .Q (b_reg[6]), .QN
       (UNCONNECTED34));
  DFFX1 \b_reg_reg[5] (.CK (clk), .D (b[5]), .Q (b_reg[5]), .QN
       (UNCONNECTED35));
  DFFX1 \a_reg_reg[17] (.CK (clk), .D (a[17]), .Q (a_reg[17]), .QN
       (n_0));
  DFFX1 \a_reg_reg[2] (.CK (clk), .D (a[2]), .Q (a_reg[2]), .QN (n_9));
  DFFX1 \b_reg_reg[4] (.CK (clk), .D (b[4]), .Q (b_reg[4]), .QN
       (UNCONNECTED36));
  DFFX1 \b_reg_reg[3] (.CK (clk), .D (b[3]), .Q (b_reg[3]), .QN (n_14));
  DFFX1 \a_reg_reg[1] (.CK (clk), .D (a[1]), .Q (a_reg[1]), .QN (n_25));
  DFFX1 \b_reg_reg[2] (.CK (clk), .D (b[2]), .Q (b_reg[2]), .QN
       (UNCONNECTED37));
  DFFX1 \b_reg_reg[1] (.CK (clk), .D (b[1]), .Q (b_reg[1]), .QN
       (UNCONNECTED38));
  NAND2X1 g6803__5107(.A (n_219), .B (n_151), .Y (y[23]));
  NAND4X1 g6804__6260(.A (n_110), .B (n_104), .C (n_199), .D (n_76), .Y
       (y[19]));
  NAND4X1 g6805__4319(.A (n_113), .B (n_119), .C (n_202), .D (n_81), .Y
       (y[10]));
  OAI211X1 g6806__8428(.A0 (n_29), .A1 (n_88), .B0 (n_160), .C0
       (n_207), .Y (y[11]));
  OAI211X1 g6807__5526(.A0 (n_18), .A1 (n_88), .B0 (n_208), .C0
       (n_154), .Y (y[16]));
  OAI211X1 g6808__6783(.A0 (n_30), .A1 (n_88), .B0 (n_159), .C0
       (n_210), .Y (y[30]));
  NAND4X1 g6809__3680(.A (n_116), .B (n_108), .C (n_93), .D (n_209), .Y
       (y[1]));
  OAI221X1 g6810__1617(.A0 (n_7), .A1 (n_89), .B0 (n_17), .B1 (n_78),
       .C0 (n_213), .Y (y[26]));
  OAI221X1 g6811__2802(.A0 (n_2), .A1 (n_89), .B0 (n_0), .B1 (n_78),
       .C0 (n_215), .Y (y[18]));
  NAND2X1 g6812__1705(.A (n_214), .B (n_148), .Y (y[22]));
  OAI211X1 g6813__5122(.A0 (n_21), .A1 (n_89), .B0 (n_91), .C0 (n_212),
       .Y (y[28]));
  OAI211X1 g6814__8246(.A0 (n_8), .A1 (n_89), .B0 (n_92), .C0 (n_211),
       .Y (y[14]));
  NAND3X1 g6815__7098(.A (n_156), .B (n_206), .C (n_147), .Y (y[21]));
  NAND3X1 g6816__6131(.A (n_157), .B (n_205), .C (n_136), .Y (y[27]));
  NAND3X1 g6817__1881(.A (n_158), .B (n_204), .C (n_152), .Y (y[15]));
  NAND3X1 g6818__5115(.A (n_155), .B (n_203), .C (n_144), .Y (y[8]));
  AOI222X1 g6819__7482(.A0 (a_reg[22]), .A1 (n_79), .B0 (a_reg[23]),
       .B1 (n_198), .C0 (b_reg[23]), .C1 (n_166), .Y (n_219));
  NAND4X1 g6820__4733(.A (n_111), .B (n_137), .C (n_192), .D (n_169),
       .Y (y[7]));
  NAND2X1 g6821__6161(.A (n_201), .B (n_150), .Y (y[31]));
  NAND4X1 g6822__9315(.A (n_118), .B (n_142), .C (n_197), .D (n_174),
       .Y (y[4]));
  NAND4X1 g6823__9945(.A (n_115), .B (n_140), .C (n_195), .D (n_171),
       .Y (y[13]));
  NAND4X1 g6824__2883(.A (n_114), .B (n_139), .C (n_194), .D (n_170),
       .Y (y[12]));
  NAND4X1 g6825__2346(.A (n_112), .B (n_138), .C (n_193), .D (n_173),
       .Y (y[29]));
  NAND2X1 g6826__1666(.A (n_200), .B (n_153), .Y (y[0]));
  NAND4X1 g6827__7410(.A (n_109), .B (n_149), .C (n_191), .D (n_168),
       .Y (y[6]));
  NAND4X1 g6828__6417(.A (n_106), .B (n_143), .C (n_190), .D (n_162),
       .Y (y[5]));
  NAND4X1 g6829__5477(.A (n_117), .B (n_141), .C (n_196), .D (n_172),
       .Y (y[17]));
  NAND3X1 g6830__2398(.A (n_145), .B (n_134), .C (n_186), .Y (y[9]));
  OAI211X1 g6831__5107(.A0 (n_14), .A1 (n_130), .B0 (n_135), .C0
       (n_182), .Y (y[3]));
  INVX1 g6832(.A (n_218), .Y (y[2]));
  INVX1 g6833(.A (n_217), .Y (y[24]));
  INVX1 g6834(.A (n_216), .Y (y[25]));
  OAI211X1 g6835__6260(.A0 (n_26), .A1 (n_107), .B0 (n_176), .C0
       (n_146), .Y (y[20]));
  AOI221X1 g6836__4319(.A0 (b_reg[2]), .A1 (n_129), .B0 (a_reg[3]), .B1
       (n_90), .C0 (n_181), .Y (n_218));
  AOI221X1 g6837__8428(.A0 (b_reg[24]), .A1 (n_125), .B0 (n_47), .B1
       (u_alu_n_370), .C0 (n_179), .Y (n_217));
  AOI221X1 g6838__5526(.A0 (b_reg[25]), .A1 (n_131), .B0 (a_reg[26]),
       .B1 (n_90), .C0 (n_189), .Y (n_216));
  AOI222X1 g6839__6783(.A0 (b_reg[18]), .A1 (n_185), .B0 (a_reg[18]),
       .B1 (n_167), .C0 (n_47), .C1 (u_alu_n_376), .Y (n_215));
  AOI222X1 g6840__3680(.A0 (a_reg[22]), .A1 (n_165), .B0 (a_reg[23]),
       .B1 (n_90), .C0 (b_reg[22]), .C1 (n_184), .Y (n_214));
  AOI222X1 g6841__1617(.A0 (b_reg[26]), .A1 (n_183), .B0 (a_reg[26]),
       .B1 (n_164), .C0 (n_47), .C1 (u_alu_n_368), .Y (n_213));
  AOI221X1 g6842__2802(.A0 (a_reg[27]), .A1 (n_79), .B0 (a_reg[28]),
       .B1 (n_87), .C0 (n_188), .Y (n_212));
  AOI221X1 g6843__1705(.A0 (a_reg[13]), .A1 (n_79), .B0 (a_reg[14]),
       .B1 (n_87), .C0 (n_187), .Y (n_211));
  AOI222X1 g6844__5122(.A0 (a_reg[31]), .A1 (n_90), .B0 (b_reg[30]),
       .B1 (n_128), .C0 (n_47), .C1 (u_alu_n_364), .Y (n_210));
  AOI222X1 g6845__8246(.A0 (a_reg[2]), .A1 (n_90), .B0 (a_reg[1]), .B1
       (n_133), .C0 (n_47), .C1 (u_alu_n_393), .Y (n_209));
  AOI222X1 g6846__7098(.A0 (n_53), .A1 (n_86), .B0 (a_reg[17]), .B1
       (n_90), .C0 (b_reg[16]), .C1 (n_180), .Y (n_208));
  AOI222X1 g6847__6131(.A0 (a_reg[12]), .A1 (n_90), .B0 (b_reg[11]),
       .B1 (n_127), .C0 (n_47), .C1 (u_alu_n_383), .Y (n_207));
  AOI222X1 g6848__1881(.A0 (n_27), .A1 (n_87), .B0 (n_71), .B1 (n_86),
       .C0 (a_reg[22]), .C1 (n_90), .Y (n_206));
  AOI222X1 g6849__5115(.A0 (n_37), .A1 (n_87), .B0 (n_72), .B1 (n_86),
       .C0 (a_reg[28]), .C1 (n_90), .Y (n_205));
  AOI222X1 g6850__7482(.A0 (n_36), .A1 (n_87), .B0 (n_73), .B1 (n_86),
       .C0 (a_reg[16]), .C1 (n_90), .Y (n_204));
  AOI222X1 g6851__4733(.A0 (n_31), .A1 (n_87), .B0 (n_74), .B1 (n_86),
       .C0 (a_reg[9]), .C1 (n_90), .Y (n_203));
  AOI222X1 g6852__6161(.A0 (n_42), .A1 (n_86), .B0 (a_reg[11]), .B1
       (n_90), .C0 (b_reg[10]), .C1 (n_126), .Y (n_202));
  AOI222X1 g6853__9315(.A0 (n_123), .A1 (n_86), .B0 (n_122), .B1
       (n_67), .C0 (n_46), .C1 (n_87), .Y (n_201));
  AOI222X1 g6854__9945(.A0 (n_121), .A1 (n_86), .B0 (n_120), .B1
       (n_67), .C0 (n_38), .C1 (n_87), .Y (n_200));
  AOI222X1 g6855__2883(.A0 (n_34), .A1 (n_86), .B0 (a_reg[18]), .B1
       (n_79), .C0 (b_reg[19]), .C1 (n_124), .Y (n_199));
  NAND2X1 g6856__2346(.A (n_88), .B (n_132), .Y (n_198));
  AOI22X1 g6857__1666(.A0 (b_reg[4]), .A1 (n_94), .B0 (n_57), .B1
       (n_86), .Y (n_197));
  AOI22X1 g6858__7410(.A0 (b_reg[17]), .A1 (n_102), .B0 (n_50), .B1
       (n_86), .Y (n_196));
  AOI22X1 g6859__6417(.A0 (b_reg[13]), .A1 (n_99), .B0 (n_63), .B1
       (n_86), .Y (n_195));
  AOI22X1 g6860__5477(.A0 (b_reg[12]), .A1 (n_105), .B0 (n_66), .B1
       (n_86), .Y (n_194));
  AOI22X1 g6861__2398(.A0 (b_reg[29]), .A1 (n_97), .B0 (n_60), .B1
       (n_86), .Y (n_193));
  AOI22X1 g6862__5107(.A0 (b_reg[7]), .A1 (n_95), .B0 (n_52), .B1
       (n_86), .Y (n_192));
  AOI22X1 g6863__6260(.A0 (b_reg[6]), .A1 (n_96), .B0 (n_41), .B1
       (n_86), .Y (n_191));
  AOI22X1 g6864__4319(.A0 (b_reg[5]), .A1 (n_103), .B0 (n_64), .B1
       (n_86), .Y (n_190));
  OAI211X1 g6865__8428(.A0 (n_28), .A1 (n_88), .B0 (n_161), .C0 (n_80),
       .Y (n_189));
  INVX1 g6866(.A (n_178), .Y (n_188));
  INVX1 g6867(.A (n_177), .Y (n_187));
  AOI22X1 g6868__5526(.A0 (a_reg[9]), .A1 (n_98), .B0 (n_47), .B1
       (u_alu_n_385), .Y (n_186));
  OAI211X1 g6869__6783(.A0 (a_reg[18]), .A1 (n_85), .B0 (n_82), .C0
       (n_88), .Y (n_185));
  OAI211X1 g6870__3680(.A0 (a_reg[22]), .A1 (n_85), .B0 (n_84), .C0
       (n_88), .Y (n_184));
  OAI211X1 g6871__1617(.A0 (a_reg[26]), .A1 (n_85), .B0 (n_75), .C0
       (n_88), .Y (n_183));
  AOI222X1 g6872__2802(.A0 (n_43), .A1 (n_86), .B0 (n_33), .B1 (n_87),
       .C0 (n_47), .C1 (u_alu_n_391), .Y (n_182));
  OAI211X1 g6873__1705(.A0 (n_32), .A1 (n_88), .B0 (n_175), .C0 (n_83),
       .Y (n_181));
  OAI221X1 g6874__5122(.A0 (a_reg[16]), .A1 (n_85), .B0 (n_18), .B1
       (n_68), .C0 (n_88), .Y (n_180));
  OAI221X1 g6875__8246(.A0 (n_35), .A1 (n_88), .B0 (n_17), .B1 (n_89),
       .C0 (n_163), .Y (n_179));
  AOI222X1 g6876__7098(.A0 (b_reg[28]), .A1 (n_101), .B0 (n_48), .B1
       (n_86), .C0 (n_47), .C1 (u_alu_n_366), .Y (n_178));
  AOI222X1 g6877__6131(.A0 (b_reg[14]), .A1 (n_100), .B0 (n_49), .B1
       (n_86), .C0 (n_47), .C1 (u_alu_n_380), .Y (n_177));
  AOI222X1 g6878__1881(.A0 (b_reg[20]), .A1 (n_87), .B0 (n_70), .B1
       (n_86), .C0 (a_reg[21]), .C1 (n_90), .Y (n_176));
  AOI22X1 g6879__5115(.A0 (n_61), .A1 (n_86), .B0 (a_reg[1]), .B1
       (n_79), .Y (n_175));
  AOI22X1 g6880__7482(.A0 (n_59), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_390), .Y (n_174));
  AOI22X1 g6881__4733(.A0 (n_56), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_365), .Y (n_173));
  AOI22X1 g6882__6161(.A0 (n_58), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_377), .Y (n_172));
  AOI22X1 g6883__9315(.A0 (n_45), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_381), .Y (n_171));
  AOI22X1 g6884__9945(.A0 (n_44), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_382), .Y (n_170));
  AOI22X1 g6885__2883(.A0 (n_55), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_387), .Y (n_169));
  AOI22X1 g6886__2346(.A0 (n_39), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_388), .Y (n_168));
  OAI21X1 g6887__1666(.A0 (b_reg[18]), .A1 (n_85), .B0 (n_88), .Y
       (n_167));
  OAI21X1 g6888__7410(.A0 (a_reg[23]), .A1 (n_85), .B0 (n_88), .Y
       (n_166));
  OAI21X1 g6889__6417(.A0 (b_reg[22]), .A1 (n_85), .B0 (n_88), .Y
       (n_165));
  OAI21X1 g6890__5477(.A0 (b_reg[26]), .A1 (n_85), .B0 (n_88), .Y
       (n_164));
  AOI22X1 g6891__2398(.A0 (n_54), .A1 (n_86), .B0 (a_reg[23]), .B1
       (n_79), .Y (n_163));
  AOI22X1 g6892__5107(.A0 (n_51), .A1 (n_86), .B0 (n_47), .B1
       (u_alu_n_389), .Y (n_162));
  AOI22X1 g6893__6260(.A0 (n_40), .A1 (n_86), .B0 (a_reg[24]), .B1
       (n_79), .Y (n_161));
  AOI22X1 g6894__4319(.A0 (n_62), .A1 (n_86), .B0 (a_reg[10]), .B1
       (n_79), .Y (n_160));
  AOI22X1 g6895__8428(.A0 (n_65), .A1 (n_86), .B0 (a_reg[29]), .B1
       (n_79), .Y (n_159));
  NAND3X1 g6896__5526(.A (b_reg[15]), .B (a_reg[15]), .C (n_67), .Y
       (n_158));
  NAND3X1 g6897__6783(.A (b_reg[27]), .B (a_reg[27]), .C (n_67), .Y
       (n_157));
  NAND3X1 g6898__3680(.A (b_reg[21]), .B (a_reg[21]), .C (n_67), .Y
       (n_156));
  NAND3X1 g6899__1617(.A (b_reg[8]), .B (a_reg[8]), .C (n_67), .Y
       (n_155));
  AOI22X1 g6900__2802(.A0 (a_reg[15]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_378), .Y (n_154));
  AOI22X1 g6901__1705(.A0 (a_reg[1]), .A1 (n_90), .B0 (n_47), .B1
       (u_alu_n_394), .Y (n_153));
  AOI22X1 g6902__5122(.A0 (a_reg[14]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_379), .Y (n_152));
  AOI22X1 g6903__8246(.A0 (a_reg[24]), .A1 (n_90), .B0 (n_47), .B1
       (u_alu_n_371), .Y (n_151));
  AOI22X1 g6904__7098(.A0 (a_reg[30]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_363), .Y (n_150));
  AOI22X1 g6905__6131(.A0 (a_reg[6]), .A1 (n_87), .B0 (a_reg[5]), .B1
       (n_79), .Y (n_149));
  AOI22X1 g6906__1881(.A0 (a_reg[21]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_372), .Y (n_148));
  AOI22X1 g6907__5115(.A0 (a_reg[20]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_373), .Y (n_147));
  AOI22X1 g6908__7482(.A0 (a_reg[19]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_374), .Y (n_146));
  AOI22X1 g6909__4733(.A0 (a_reg[10]), .A1 (n_90), .B0 (b_reg[9]), .B1
       (n_87), .Y (n_145));
  AOI22X1 g6910__6161(.A0 (a_reg[7]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_386), .Y (n_144));
  AOI22X1 g6911__9315(.A0 (a_reg[5]), .A1 (n_87), .B0 (a_reg[4]), .B1
       (n_79), .Y (n_143));
  AOI22X1 g6912__9945(.A0 (a_reg[4]), .A1 (n_87), .B0 (a_reg[3]), .B1
       (n_79), .Y (n_142));
  AOI22X1 g6913__2883(.A0 (a_reg[17]), .A1 (n_87), .B0 (a_reg[16]), .B1
       (n_79), .Y (n_141));
  AOI22X1 g6914__2346(.A0 (a_reg[13]), .A1 (n_87), .B0 (a_reg[12]), .B1
       (n_79), .Y (n_140));
  AOI22X1 g6915__1666(.A0 (a_reg[12]), .A1 (n_87), .B0 (a_reg[11]), .B1
       (n_79), .Y (n_139));
  AOI22X1 g6916__7410(.A0 (a_reg[29]), .A1 (n_87), .B0 (a_reg[28]), .B1
       (n_79), .Y (n_138));
  AOI22X1 g6917__6417(.A0 (a_reg[7]), .A1 (n_87), .B0 (a_reg[6]), .B1
       (n_79), .Y (n_137));
  AOI22X1 g6918__5477(.A0 (a_reg[26]), .A1 (n_79), .B0 (n_47), .B1
       (u_alu_n_367), .Y (n_136));
  AOI22X1 g6919__2398(.A0 (a_reg[4]), .A1 (n_90), .B0 (a_reg[2]), .B1
       (n_79), .Y (n_135));
  AOI22X1 g6920__5107(.A0 (n_77), .A1 (n_86), .B0 (a_reg[8]), .B1
       (n_79), .Y (n_134));
  MX2X1 g6921__6260(.A (n_86), .B (n_67), .S0 (b_reg[1]), .Y (n_133));
  MX2X1 g6922__4319(.A (n_85), .B (n_68), .S0 (b_reg[23]), .Y (n_132));
  OAI22X1 g6923__8428(.A0 (a_reg[25]), .A1 (n_85), .B0 (n_17), .B1
       (n_68), .Y (n_131));
  AOI22X1 g6924__5526(.A0 (n_22), .A1 (n_86), .B0 (a_reg[3]), .B1
       (n_67), .Y (n_130));
  OAI22X1 g6925__6783(.A0 (a_reg[2]), .A1 (n_85), .B0 (n_9), .B1
       (n_68), .Y (n_129));
  OAI22X1 g6926__3680(.A0 (a_reg[30]), .A1 (n_85), .B0 (n_5), .B1
       (n_68), .Y (n_128));
  OAI22X1 g6927__1617(.A0 (a_reg[11]), .A1 (n_85), .B0 (n_4), .B1
       (n_68), .Y (n_127));
  OAI22X1 g6928__2802(.A0 (a_reg[10]), .A1 (n_85), .B0 (n_15), .B1
       (n_68), .Y (n_126));
  OAI22X1 g6929__1705(.A0 (a_reg[24]), .A1 (n_85), .B0 (n_24), .B1
       (n_68), .Y (n_125));
  OAI22X1 g6930__5122(.A0 (a_reg[19]), .A1 (n_85), .B0 (n_2), .B1
       (n_68), .Y (n_124));
  ADDHX1 g6931__8246(.A (b_reg[31]), .B (a_reg[31]), .CO (n_122), .S
       (n_123));
  ADDHX1 g6932__7098(.A (b_reg[0]), .B (a_reg[0]), .CO (n_120), .S
       (n_121));
  OAI21X1 g6933__6131(.A0 (b_reg[10]), .A1 (a_reg[10]), .B0 (n_87), .Y
       (n_119));
  NAND2X1 g6934__1881(.A (a_reg[5]), .B (n_90), .Y (n_118));
  NAND2X1 g6935__5115(.A (a_reg[18]), .B (n_90), .Y (n_117));
  NAND2X1 g6936__7482(.A (a_reg[0]), .B (n_79), .Y (n_116));
  NAND2X1 g6937__4733(.A (a_reg[14]), .B (n_90), .Y (n_115));
  NAND2X1 g6938__6161(.A (a_reg[13]), .B (n_90), .Y (n_114));
  NAND2X1 g6939__9315(.A (a_reg[9]), .B (n_79), .Y (n_113));
  NAND2X1 g6940__9945(.A (a_reg[30]), .B (n_90), .Y (n_112));
  NAND2X1 g6941__2883(.A (a_reg[8]), .B (n_90), .Y (n_111));
  NAND2X1 g6942__2346(.A (a_reg[20]), .B (n_90), .Y (n_110));
  NAND2X1 g6943__1666(.A (a_reg[7]), .B (n_90), .Y (n_109));
  OAI21X1 g6944__7410(.A0 (b_reg[1]), .A1 (a_reg[1]), .B0 (n_87), .Y
       (n_108));
  AOI21X1 g6945__6417(.A0 (b_reg[20]), .A1 (n_67), .B0 (n_87), .Y
       (n_107));
  NAND2X1 g6946__5477(.A (a_reg[6]), .B (n_90), .Y (n_106));
  OAI21X1 g6947__2398(.A0 (n_23), .A1 (n_68), .B0 (n_88), .Y (n_105));
  OAI21X1 g6948__5107(.A0 (b_reg[19]), .A1 (a_reg[19]), .B0 (n_87), .Y
       (n_104));
  OAI21X1 g6949__6260(.A0 (n_19), .A1 (n_68), .B0 (n_88), .Y (n_103));
  OAI21X1 g6950__4319(.A0 (n_0), .A1 (n_68), .B0 (n_88), .Y (n_102));
  OAI21X1 g6951__8428(.A0 (n_3), .A1 (n_68), .B0 (n_88), .Y (n_101));
  OAI21X1 g6952__5526(.A0 (n_16), .A1 (n_68), .B0 (n_88), .Y (n_100));
  OAI21X1 g6953__6783(.A0 (n_10), .A1 (n_68), .B0 (n_88), .Y (n_99));
  OAI21X1 g6954__3680(.A0 (n_12), .A1 (n_68), .B0 (n_88), .Y (n_98));
  OAI21X1 g6955__1617(.A0 (n_21), .A1 (n_68), .B0 (n_88), .Y (n_97));
  OAI21X1 g6956__2802(.A0 (n_20), .A1 (n_68), .B0 (n_88), .Y (n_96));
  OAI21X1 g6957__1705(.A0 (n_6), .A1 (n_68), .B0 (n_88), .Y (n_95));
  OAI21X1 g6958__5122(.A0 (n_1), .A1 (n_68), .B0 (n_88), .Y (n_94));
  NAND3X1 g6959__8246(.A (b_reg[1]), .B (n_25), .C (n_86), .Y (n_93));
  NAND3X1 g6960__7098(.A (b_reg[14]), .B (n_16), .C (n_86), .Y (n_92));
  NAND3X1 g6961__6131(.A (b_reg[28]), .B (n_3), .C (n_86), .Y (n_91));
  CLKINVX2 g6962(.A (n_90), .Y (n_89));
  INVX2 g6963(.A (n_88), .Y (n_87));
  INVX2 g6964(.A (n_86), .Y (n_85));
  NAND2X1 g6965__1881(.A (a_reg[22]), .B (n_67), .Y (n_84));
  NAND2X1 g6966__5115(.A (n_47), .B (u_alu_n_392), .Y (n_83));
  NAND2X1 g6967__7482(.A (a_reg[18]), .B (n_67), .Y (n_82));
  NAND2X1 g6968__4733(.A (n_47), .B (u_alu_n_384), .Y (n_81));
  NAND2X1 g6969__6161(.A (n_47), .B (u_alu_n_369), .Y (n_80));
  CLKAND2X2 g6970__9315(.A (op_reg[1]), .B (n_69), .Y (n_90));
  NAND2X2 g6971__9945(.A (op_reg[0]), .B (n_67), .Y (n_88));
  CLKAND2X2 g6972__2883(.A (n_11), .B (n_69), .Y (n_86));
  INVX1 g6973(.A (n_79), .Y (n_78));
  CLKXOR2X1 g6974__2346(.A (a_reg[9]), .B (b_reg[9]), .Y (n_77));
  NAND2X1 g6975__1666(.A (n_47), .B (u_alu_n_375), .Y (n_76));
  NAND2X1 g6976__7410(.A (a_reg[26]), .B (n_67), .Y (n_75));
  CLKXOR2X1 g6977__6417(.A (b_reg[8]), .B (a_reg[8]), .Y (n_74));
  CLKXOR2X1 g6978__5477(.A (b_reg[15]), .B (a_reg[15]), .Y (n_73));
  CLKXOR2X1 g6979__2398(.A (b_reg[27]), .B (a_reg[27]), .Y (n_72));
  CLKXOR2X1 g6980__5107(.A (b_reg[21]), .B (a_reg[21]), .Y (n_71));
  CLKXOR2X1 g6981__6260(.A (b_reg[20]), .B (a_reg[20]), .Y (n_70));
  AND3X2 g6982__4319(.A (op_reg[2]), .B (op_reg[0]), .C (n_11), .Y
       (n_79));
  CLKINVX2 g6983(.A (n_68), .Y (n_67));
  NOR2X1 g6984__8428(.A (b_reg[12]), .B (n_23), .Y (n_66));
  NOR2X1 g6985__5526(.A (b_reg[30]), .B (n_5), .Y (n_65));
  NOR2X1 g6986__6783(.A (b_reg[5]), .B (n_19), .Y (n_64));
  NOR2X1 g6987__3680(.A (b_reg[13]), .B (n_10), .Y (n_63));
  NOR2X1 g6988__1617(.A (b_reg[11]), .B (n_4), .Y (n_62));
  NOR2X1 g6989__2802(.A (b_reg[2]), .B (n_9), .Y (n_61));
  NOR2X1 g6990__1705(.A (b_reg[29]), .B (n_21), .Y (n_60));
  AND2X1 g6991__5122(.A (n_1), .B (b_reg[4]), .Y (n_59));
  AND2X1 g6992__8246(.A (n_0), .B (b_reg[17]), .Y (n_58));
  NOR2X1 g6993__7098(.A (b_reg[4]), .B (n_1), .Y (n_57));
  AND2X1 g6994__6131(.A (n_21), .B (b_reg[29]), .Y (n_56));
  AND2X1 g6995__1881(.A (n_6), .B (b_reg[7]), .Y (n_55));
  NOR2X1 g6996__5115(.A (b_reg[24]), .B (n_24), .Y (n_54));
  NOR2X1 g6997__7482(.A (b_reg[16]), .B (n_18), .Y (n_53));
  NOR2X1 g6998__4733(.A (b_reg[7]), .B (n_6), .Y (n_52));
  AND2X1 g6999__6161(.A (n_19), .B (b_reg[5]), .Y (n_51));
  NOR2X1 g7000__9315(.A (b_reg[17]), .B (n_0), .Y (n_50));
  NOR2X1 g7001__9945(.A (b_reg[14]), .B (n_16), .Y (n_49));
  NOR2X1 g7002__2883(.A (b_reg[28]), .B (n_3), .Y (n_48));
  NOR2X1 g7003__2346(.A (op_reg[0]), .B (n_13), .Y (n_69));
  OR2X2 g7004__1666(.A (op_reg[2]), .B (n_11), .Y (n_68));
  OR2X1 g7005__7410(.A (a_reg[31]), .B (b_reg[31]), .Y (n_46));
  AND2X1 g7006__6417(.A (n_10), .B (b_reg[13]), .Y (n_45));
  AND2X1 g7007__5477(.A (n_23), .B (b_reg[12]), .Y (n_44));
  NOR2X1 g7008__2398(.A (b_reg[3]), .B (n_22), .Y (n_43));
  NOR2X1 g7009__5107(.A (b_reg[10]), .B (n_15), .Y (n_42));
  NOR2X1 g7010__6260(.A (b_reg[6]), .B (n_20), .Y (n_41));
  NOR2X1 g7011__4319(.A (b_reg[25]), .B (n_17), .Y (n_40));
  AND2X1 g7012__8428(.A (n_20), .B (b_reg[6]), .Y (n_39));
  OR2X1 g7013__5526(.A (a_reg[0]), .B (b_reg[0]), .Y (n_38));
  OR2X1 g7014__6783(.A (a_reg[27]), .B (b_reg[27]), .Y (n_37));
  OR2X1 g7015__3680(.A (a_reg[15]), .B (b_reg[15]), .Y (n_36));
  NOR2X1 g7016__1617(.A (b_reg[24]), .B (a_reg[24]), .Y (n_35));
  NOR2X1 g7017__2802(.A (b_reg[19]), .B (n_2), .Y (n_34));
  NAND2X1 g7018__1705(.A (n_14), .B (n_22), .Y (n_33));
  NOR2X1 g7019__5122(.A (b_reg[2]), .B (a_reg[2]), .Y (n_32));
  OR2X1 g7020__8246(.A (a_reg[8]), .B (b_reg[8]), .Y (n_31));
  NOR2X1 g7021__7098(.A (a_reg[30]), .B (b_reg[30]), .Y (n_30));
  NOR2X1 g7022__6131(.A (a_reg[11]), .B (b_reg[11]), .Y (n_29));
  NOR2X1 g7023__1881(.A (b_reg[25]), .B (a_reg[25]), .Y (n_28));
  OR2X1 g7024__5115(.A (a_reg[21]), .B (b_reg[21]), .Y (n_27));
  AND2X2 g7025__7482(.A (n_13), .B (n_11), .Y (n_47));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g956__4733(.A
       (u_alu_sub_11_23_Y_add_10_23_n_773), .B
       (u_alu_sub_11_23_Y_add_10_23_n_834), .Y (u_alu_n_363));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g957__6161(.A (a_reg[30]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_847), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_775), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_773), .S (u_alu_n_364));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g958__9315(.A (a_reg[29]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_861), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_777), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_775), .S (u_alu_n_365));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g959__9945(.A (a_reg[28]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_851), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_779), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_777), .S (u_alu_n_366));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g960__2883(.A (a_reg[27]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_844), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_781), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_779), .S (u_alu_n_367));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g961__2346(.A (a_reg[26]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_863), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_783), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_781), .S (u_alu_n_368));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g962__1666(.A (a_reg[25]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_865), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_785), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_783), .S (u_alu_n_369));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g963__7410(.A (a_reg[24]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_840), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_787), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_785), .S (u_alu_n_370));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g964__6417(.A (a_reg[23]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_855), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_789), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_787), .S (u_alu_n_371));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g965__5477(.A (a_reg[22]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_845), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_791), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_789), .S (u_alu_n_372));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g966__2398(.A (a_reg[21]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_858), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_793), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_791), .S (u_alu_n_373));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g967__5107(.A (a_reg[20]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_866), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_795), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_793), .S (u_alu_n_374));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g968__6260(.A (a_reg[19]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_853), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_797), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_795), .S (u_alu_n_375));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g969__4319(.A (a_reg[18]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_857), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_799), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_797), .S (u_alu_n_376));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g970__8428(.A (a_reg[17]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_838), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_801), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_799), .S (u_alu_n_377));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g971__5526(.A (a_reg[16]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_843), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_803), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_801), .S (u_alu_n_378));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g972__6783(.A (a_reg[15]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_862), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_805), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_803), .S (u_alu_n_379));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g973__3680(.A (a_reg[14]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_848), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_807), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_805), .S (u_alu_n_380));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g974__1617(.A (a_reg[13]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_842), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_809), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_807), .S (u_alu_n_381));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g975__2802(.A (a_reg[12]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_867), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_811), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_809), .S (u_alu_n_382));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g976__1705(.A (a_reg[11]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_859), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_813), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_811), .S (u_alu_n_383));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g977__5122(.A (a_reg[10]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_856), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_815), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_813), .S (u_alu_n_384));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g978__8246(.A (a_reg[9]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_854), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_817), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_815), .S (u_alu_n_385));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g979__7098(.A (a_reg[8]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_860), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_819), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_817), .S (u_alu_n_386));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g980__6131(.A (a_reg[7]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_849), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_821), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_819), .S (u_alu_n_387));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g981__1881(.A (a_reg[6]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_850), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_823), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_821), .S (u_alu_n_388));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g982__5115(.A (a_reg[5]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_864), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_825), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_823), .S (u_alu_n_389));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g983__7482(.A (a_reg[4]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_852), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_827), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_825), .S (u_alu_n_390));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g984__4733(.A (a_reg[3]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_846), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_829), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_827), .S (u_alu_n_391));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g985__6161(.A (a_reg[2]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_839), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_831), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_829), .S (u_alu_n_392));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g986__9315(.A (a_reg[1]), .B
       (u_alu_sub_11_23_Y_add_10_23_n_841), .CI
       (u_alu_sub_11_23_Y_add_10_23_n_833), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_831), .S (u_alu_n_393));
  ADDFX1 u_alu_sub_11_23_Y_add_10_23_g987__9945(.A (a_reg[0]), .B
       (n_290), .CI (u_alu_sub_11_23_Y_add_10_23_n_837), .CO
       (u_alu_sub_11_23_Y_add_10_23_n_833), .S (u_alu_n_394));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g988__2883(.A
       (u_alu_sub_11_23_Y_add_10_23_n_835), .B (a_reg[31]), .Y
       (u_alu_sub_11_23_Y_add_10_23_n_834));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g989__2346(.A (n_290), .B
       (b_reg[31]), .Y (u_alu_sub_11_23_Y_add_10_23_n_835));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g990__1666(.A (n_290), .B
       (b_reg[0]), .Y (u_alu_sub_11_23_Y_add_10_23_n_837));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g991__7410(.A (n_290), .B
       (b_reg[17]), .Y (u_alu_sub_11_23_Y_add_10_23_n_838));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g992__6417(.A (n_290), .B
       (b_reg[2]), .Y (u_alu_sub_11_23_Y_add_10_23_n_839));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g993__5477(.A (n_290), .B
       (b_reg[24]), .Y (u_alu_sub_11_23_Y_add_10_23_n_840));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g994__2398(.A (n_290), .B
       (b_reg[1]), .Y (u_alu_sub_11_23_Y_add_10_23_n_841));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g995__5107(.A (n_290), .B
       (b_reg[13]), .Y (u_alu_sub_11_23_Y_add_10_23_n_842));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g996__6260(.A (n_290), .B
       (b_reg[16]), .Y (u_alu_sub_11_23_Y_add_10_23_n_843));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g997__4319(.A (n_290), .B
       (b_reg[27]), .Y (u_alu_sub_11_23_Y_add_10_23_n_844));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g998__8428(.A (n_290), .B
       (b_reg[22]), .Y (u_alu_sub_11_23_Y_add_10_23_n_845));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g999__5526(.A (n_290), .B
       (b_reg[3]), .Y (u_alu_sub_11_23_Y_add_10_23_n_846));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1000__6783(.A (n_290), .B
       (b_reg[30]), .Y (u_alu_sub_11_23_Y_add_10_23_n_847));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1001__3680(.A (n_290), .B
       (b_reg[14]), .Y (u_alu_sub_11_23_Y_add_10_23_n_848));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1002__1617(.A (n_290), .B
       (b_reg[7]), .Y (u_alu_sub_11_23_Y_add_10_23_n_849));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1003__2802(.A (n_290), .B
       (b_reg[6]), .Y (u_alu_sub_11_23_Y_add_10_23_n_850));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1004__1705(.A (n_290), .B
       (b_reg[28]), .Y (u_alu_sub_11_23_Y_add_10_23_n_851));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1005__5122(.A (n_290), .B
       (b_reg[4]), .Y (u_alu_sub_11_23_Y_add_10_23_n_852));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1006__8246(.A (n_290), .B
       (b_reg[19]), .Y (u_alu_sub_11_23_Y_add_10_23_n_853));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1007__7098(.A (n_290), .B
       (b_reg[9]), .Y (u_alu_sub_11_23_Y_add_10_23_n_854));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1008__6131(.A (n_290), .B
       (b_reg[23]), .Y (u_alu_sub_11_23_Y_add_10_23_n_855));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1009__1881(.A (n_290), .B
       (b_reg[10]), .Y (u_alu_sub_11_23_Y_add_10_23_n_856));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1010__5115(.A (n_290), .B
       (b_reg[18]), .Y (u_alu_sub_11_23_Y_add_10_23_n_857));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1011__7482(.A (n_290), .B
       (b_reg[21]), .Y (u_alu_sub_11_23_Y_add_10_23_n_858));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1012__4733(.A (n_290), .B
       (b_reg[11]), .Y (u_alu_sub_11_23_Y_add_10_23_n_859));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1013__6161(.A (n_290), .B
       (b_reg[8]), .Y (u_alu_sub_11_23_Y_add_10_23_n_860));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1014__9315(.A (n_290), .B
       (b_reg[29]), .Y (u_alu_sub_11_23_Y_add_10_23_n_861));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1015__9945(.A (n_290), .B
       (b_reg[15]), .Y (u_alu_sub_11_23_Y_add_10_23_n_862));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1016__2883(.A (n_290), .B
       (b_reg[26]), .Y (u_alu_sub_11_23_Y_add_10_23_n_863));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1017__2346(.A (n_290), .B
       (b_reg[5]), .Y (u_alu_sub_11_23_Y_add_10_23_n_864));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1018__1666(.A (n_290), .B
       (b_reg[25]), .Y (u_alu_sub_11_23_Y_add_10_23_n_865));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1019__7410(.A (n_290), .B
       (b_reg[20]), .Y (u_alu_sub_11_23_Y_add_10_23_n_866));
  CLKXOR2X1 u_alu_sub_11_23_Y_add_10_23_g1020__6417(.A (n_290), .B
       (b_reg[12]), .Y (u_alu_sub_11_23_Y_add_10_23_n_867));
  CLKAND2X2 g2(.A (op_reg[0]), .B (n_11), .Y (n_290));
endmodule

